spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendar_app?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=utf8
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test04954919@gmail.com
    password: rnslklilgrtnbulj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true   # DBのsnake_case ↔ Javaのcamel case を自動変換
